export const GET_LIST = 'GET_LIST';
export const GET_SINGLE = 'GET_SINGLE';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
