const datas = {
  types: [
    {label: 'Income', value: '1'},
    {label: 'Expenses', value: '2'},
  ],
  categories: [
    {label: 'Penghasilan', value: '1'},
    {label: 'Belanja', value: '2'},
    {label: 'Ongkos', value: '3'},
    {label: 'Transfer', value: '4'},
    {label: 'Education', value: '5'},
  ],
  paymentMethod: [
    {label: 'Bank BCA', value: '1'},
    {label: 'Bank Jago', value: '2'},
    {label: 'Bank BRI', value: '3'},
    {label: 'Bank Permata', value: '4'},
    {label: 'Ovo', value: '5'},
    {label: 'Gopay', value: '6'},
    {label: 'Others', value: '7'},
  ],
  PayloadTransaction: {
    category: '',
    type: '',
    subject: '',
    desc: '',
    payment_method: '',
    payment_date: '',
    total_with_fee: '',
    fee_bank: '',
    nominal: '',
    date: new Date(),
  },
  PayloadBudget: {
    category: '',
    type: '',
    desc: '',
    nominal: 0,
    budgetExhausted: 0,
  },
  months: [
    {value: 1, label: 'January'},
    {value: 2, label: 'February'},
    {value: 3, label: 'March'},
    {value: 4, label: 'April'},
    {value: 5, label: 'May'},
    {value: 6, label: 'June'},
    {value: 7, label: 'July'},
    {value: 8, label: 'August'},
    {value: 9, label: 'September'},
    {value: 10, label: 'October'},
    {value: 11, label: 'November'},
    {value: 12, label: 'December'},
  ],
};
export default datas;
