const datas = {
  types: [
    {label: 'Income', value: '1'},
    {label: 'Expenses', value: '2'},
  ],
  categories: [
    {label: 'Penghasilan', value: '1'},
    {label: 'Belanja', value: '2'},
    {label: 'Ongkos', value: '3'},
    {label: 'Transfer', value: '4'},
    {label: 'Education', value: '5'},
  ],
  paymentMethod: [
    {label: 'Bank BCA', value: '1'},
    {label: 'Bank Jago', value: '2'},
    {label: 'Bank BRI', value: '3'},
    {label: 'Bank Permata', value: '4'},
    {label: 'Ovo', value: '5'},
    {label: 'Gopay', value: '6'},
    {label: 'Others', value: '7'},
  ],
  PayloadTransaction: {
    category: '',
    type: '',
    subject: '',
    desc: '',
    payment_method: '',
    payment_date: '',
    total_with_fee: '',
    fee_bank: '',
    nominal: '',
    date: new Date(),
  },
  PayloadBudget: {
    category: '',
    type: '',
    desc: '',
    nominal: 0,
    budgetExhausted: 0,
  },
  months: [
    {value: 1, label: 'January'},
    {value: 2, label: 'February'},
    {value: 3, label: 'March'},
    {value: 4, label: 'April'},
    {value: 5, label: 'May'},
    {value: 6, label: 'June'},
    {value: 7, label: 'July'},
    {value: 8, label: 'August'},
    {value: 9, label: 'September'},
    {value: 10, label: 'October'},
    {value: 11, label: 'November'},
    {value: 12, label: 'December'},
  ],
  menuProfile: [
    // {
    //   icon: 'wallet-outline',
    //   label: 'Account',
    //   color: '#1a9e08',
    //   background: 'hsl(113, 95%, 93%)',
    // },
    {
      type: 'AntDesign',
      icon: 'upload',
      label: 'Export Data',
      color: '#081f9e',
      background: 'hsl(231, 95%, 93%)',
    },
    {
      icon: 'language',
      label: 'Language',
      color: '#9e9e08',
      background: 'hsl(60, 95%, 93%)',
    },
    {
      icon: 'moon-outline',
      label: 'Mode',
      color: '#8c089e',
      background: 'hsl(293, 95%, 93%)',
    },
    {
      type: 'AntDesign',
      icon: 'logout',
      label: 'Logout',
      color: '#9e0808',
      background: 'hsl(0, 95%, 93%)',
    },
  ],
};
export default datas;
